spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/secureauth}
    username: ${POSTGRES_USER:secureauth}
    password: ${POSTGRES_PASSWORD:secureauth}
  jpa:
    hibernate.ddl-auto: validate
  flyway.enabled: true
secureauth:
  jwt-secret: ${JWT_SECRET:local-development-secret-change-this-32-chars}
  access-seconds: 300
  refresh-seconds: 604800
  otp-seconds: 300
  otp-development-mode: ${OTP_DEVELOPMENT_MODE:true}
server.error.include-message: never
